name: Auto test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  server-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.16.0

      - name: build test bin
        run: zig build test --summary all

      - name: build release bin test
        run: zig build -Doptimize=ReleaseFast -DENABLE_NATIVE_ARCH=true

      - name: check
        run: zig build check
