name: Auto test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14

      - name: Cache bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFIles('web/bun.lockb', 'web/package.json') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Run Frontend Test
        run: |
          cd demo
          bun install --frozen-lockfile

  server-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.16.0

      - name: build test bin
        run: zig build test --summary all

      - name: build ReleaseFast bin test
        run: zig build -Doptimize=ReleaseFast -DENABLE_NATIVE_ARCH=true -Dtarget=x86_64-linux-gnu --summary all

      - name: build ReleaseSmall bin test
        run: zig build -Doptimize=ReleaseSmall -DENABLE_NATIVE_ARCH=true -Dtarget=x86_64-linux-gnu --summary all

      - name: check
        run: zig build check --summary all
